### ISSUE TITLE
Document `/vsigzip/` convention when reading gzip files in docstring, examples and tutorial

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa-geo#235]
Document the weird `/vsigzip/` convention when reading gzip files in docstring, examples and tutorial. So basically this piece of infromation:

> mesa-geo's `from_file()` immediately calls `rasterio.open()` without modifying the argument, you should do this:
> 
> ```python
> raster_layer = mg.RasterLayer.from_file(
>     f"/vsigzip/{elevation_file}", cell_cls=LakeCell, attr_name="elevation"
> )
> ```
> 
> Rasterio (from GDAL) has gzip support built-in: https://gdal.org/user/virtual_file_systems.html#vsigzip-gzipped-file.

Here comes the plot twist: `/vsigzip/` is _not_ part of the data path, but a weird convention by GDAL:

```
/vsigzip/my.gz # (relative path to the .gz)
/vsigzip//home/even/my.gz # (absolute path to the .gz)
/vsigzip/c:\users\even\my.gz
```
This should be thoroughly documented in Mesa-geo, since this is a very specific piece of knowledge you won't otherwise find out _and_ it's publicly exposed in our user example models.

Related tickets:
- https://github.com/projectmesa/mesa-examples/issues/172
- https://github.com/rasterio/rasterio/issues/2863

**Todo**
- [ ] Mention in tutorial
- [ ] Mention in docstring
- [ ] Mention in examples

**Comment by EwoutH** [comment]
Closed by https://github.com/projectmesa/mesa-geo/pull/237.

**Comment by wang-boyu** [comment]
This may or may not be useful - just found a method from `geopandas`: [geopandas.io.util.vsi_path](https://github.com/geopandas/geopandas/blob/3d0ff15aaa0c7e5165aecc4f33bdb3171f04d7b0/geopandas/io/util.py#L8) that adds a prefix to zipped file paths and does nothing otherwise. `geopandas` handles vector data, but this method could be handy in converting file paths for our raster data.

**Comment by EwoutH** [comment]
Oh that’s interesting!
